app_name: "relay"
app_version: "0.1.0"
app_env: "development"

clients: 
  - name: "relay-client"
    ip: "127.0.0.1"
    port: 13371


logger:
  output: "console"
  level: "debug"
  # file_path: "logs/relay.log"
  # max_size: 100
  # max_backups: 7
  # max_age: 7
  # compress: false